#include <iostream>
#include <cmath>
#include <iomanip>

int main() {
  // 1 шаг: частотный анализ текста
  // создаем строку с текстом
  std::string text = "SO FGP 1940D, FGP VSCDF CPWEYOSMHJNA NHOYQHYP CPRQSCPU H YCPHF
UPHN EV SOFPNNPWFQHN PVVECF. HO PHCNA TCETEDHN VEC H GSYG-NPBPN
TCEYCHKKSOY NHOYQHYP ZHD TNHOIHNIQN, UPBPNETPU JA IEOCHU MQDP VEC
GSD M1 WEKTQFPC JPFZPPO 1943 HOU 1945 JQF OEF SKTNPKPOFPU HF FGP FSKP.
FGP VSCDF VQOWFSEOSOY TCEYCHKKSOY NHOYQHYPD UPDSYOPU FE
WEKKQOSWHFP SODFCQWFSEOD FE H WEKTQFPC ZPCP ZCSFFPO SO FGP PHCNA
1950D. LEGO KHQWGNA\'D DGECF WEUP, TCETEDPU SO 1949, ZHD EOP EV FGP
VSCDF GSYG-NPBPN NHOYQHYPD PBPC UPBPNETPU VEC HO PNPWFCEOSW
WEKTQFPC. QONSIP KHWGSOP WEUP, DGECF WEUP DFHFPKPOFD CPTCPDPOFPU
KHFGPKHFSWHN PXTCPDDSEOD SO QOUPCDFHOUHJNP VECK. GEZPBPC, FGP
TCEYCHK GHU FE JP FCHODNHFPU SOFE KHWGSOP WEUP PBPCA FSKP SF CHO,
KHISOY FGP TCEWPDD KQWG DNEZPC FGHO CQOOSOY FGP PRQSBHNPOF
KHWGSOP WEUP. SO FGP PHCNA 1950D, HNSWI YNPOOSP UPBPNETPU HQFEWEUP,
TEDDSJNA FGP VSCDF WEKTSNPU TCEYCHKKSOY NHOYQHYP, HF FGP
QOSBPCDSFA EV KHOWGPDFPC. SO 1954, H DPWEOU SFPCHFSEO EV FGP
NHOYQHYP, IOEZO HD FGP "KHCI 1 HQFEWEUP," ZHD UPBPNETPU VEC FGP KHCI 1
JA C. H. JCEEIPC. JCEEIPC HNDE UPBPNETPU HO HQFEWEUP VEC FGP VPCCHOFS
KPCWQCA SO FGP 1950D SO WEOLQOWFSEO ZSFG FGP QOSBPCDSFA EV
KHOWGPDFPC. FGP BPCDSEO VEC FGP PUDHW 2 ZHD UPBSDPU JA UEQYNHD
GHCFCPP EV QOSBPCDSFA EV WHKJCSUYP KHFGPKHFSWHN NHJECHFECA SO
1961. IOEZO HD PUDHW 2 HQFEWEUP, SF ZHD H DFCHSYGF UPBPNETKPOF VCEK
KPCWQCA HQFEWEUP HUHTFPU VEC NEWHN WSCWQKDFHOWPD HOU ZHD
OEFPU VEC SFD EJLPWF WEUP ETFSKSMHFSEO HOU DEQCWP-NHOYQHYP
USHYOEDFSWD ZGSWG ZPCP HUBHOWPU VEC FGP FSKP. H WEOFPKTECHCA JQF
DPTHCHFP FGCPHU EV UPBPNETKPOF, HFNHD HQFEWEUP ZHD UPBPNETPU VEC
FGP QOSBPCDSFA EV KHOWGPDFPC HFNHD 1 KHWGSOP. SO 1954, VECFCHO ZHD
SOBPOFPU HF SJK JA H FPHK NPU JA LEGO JHWIQD; SF ZHD FGP VSCDF ZSUPNA
QDPU GSYG-NPBPN YPOPCHN TQCTEDP TCEYCHKKSOY NHOYQHYP FE GHBP H
VQOWFSEOHN SKTNPKPOFHFSEO, HD ETTEDPU FE LQDF H UPDSYO EO THTPC.
ZGPO VECFCHO ZHD VSCDF SOFCEUQWPU, SF ZHD BSPZPU ZSFG DIPTFSWSDK
UQP FE JQYD, UPNHAD SO UPBPNETKPOF, HOU FGP WEKTHCHFSBP PVVSWSPOWA
EV "GHOU-WEUPU" TCEYCHKD ZCSFFPO SO HDDPKJNA. GEZPBPC, SO H
GHCUZHCP KHCIPF FGHF ZHD CHTSUNA PBENBSOY; FGP NHOYQHYP
PBPOFQHNNA JPWHKP IOEZO VEC SFD PVVSWSPOWA. SF SD DFSNN H TETQNHC
NHOYQHYP VEC GSYG-TPCVECKHOWP WEKTQFSOY HOU SD QDPU VEC
TCEYCHKD FGHF JPOWGKHCI HOU CHOI FGP ZECNU\'D VHDFPDF
DQTPCWEKTQFPCD."
  int z = 0;
    for(int i : input) {
        if ((i == 'z') || (i == 'Z')) z++;
    }
  return 0;
}
